# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.

name: verify-titles
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build pdf
        run: .github/scripts/verify-titles.pl SUMMARY.md

